apiVersion: v1
kind: Service
metadata:
  name: personal-site
  labels:
    app: personal-site
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: personal-site