stages:
  - push

Push New Image:
  image: docker:stable
  services:
    - docker:19.03.5-dind
  stage: push
  only:
    - master
  before_script:
    - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  script:
    - DOCKER_CLI_EXPERIMENTAL=enabled docker buildx create --name builder --driver docker-container --use
    - DOCKER_CLI_EXPERIMENTAL=enabled docker buildx inspect --bootstrap
    - DOCKER_CLI_EXPERIMENTAL=enabled docker buildx build . -f Dockerfile.arm --platform linux/arm/v7 -t ${CI_REGISTRY}/khayyamsaleem/personalsite_v2:arm --load
    - docker push ${CI_REGISTRY}/khayyamsaleem/personalsite_v2:arm
