title = "Khayyam Saleem"
baseURL = "/"

[module]
  [[module.imports]]
    path = "github.com/colorchestra/smol"

[Menus]
  main = [
    { Name = "Github", URL = "https://github.com/khayyamsaleem" },
    { Name = "LinkedIn", URL = "https://linkedin.com/in/khayyamsaleem" },
    { Name = "Resume", URL = "/resume.pdf" }
  ]

[params]
  description = "ed-tech, functional programming, devops"
  themeColor = "theme-base-0e"
