baseURL = "https://khayyam.me/"
languageCode = "en-us"
title = "Khayyam Saleem"
theme = "hyde-hyde"
subtitle = "Educational Technology, Functional Programming, DevOps"

canonifyURLs = true
uglyurls = false
postNavigation=false
highlightjs = true


[params]
  author = "Khayyam Saleem"
  authorlinkedin = "https://www.linkedin/com/in/khayyamsaleem"
  themeColor = "theme-base-0d"
  copyright = "&copy; 2018 Khayyam Saleem"
  description = "Educational Technology, Functional Programming, DevOps"
  sidebartitle = "Khayyam Saleem"
  sidebartagline = "Educational Technology, Functional Programming, DevOps"

[params.social]
  twitter = "khayyamsaleem"
  github = "khayyamsaleem"
  linkedin = "khayyamsaleem"
  gravatar = "khayyam.saleem@gmail.com"

[[menu.main]]
  name = "Posts"
  identifier = "posts"
  url = "/posts/"


[[menu.social]]
  pre = "<i class ='fa fa-github'></i>"
  url = "https://github.com/khayyamsaleem"
  identifier = "github"

[[menu.social]]
  pre = "<i class = 'fa fa-linkedin'></i>"
  url = "https://linkedin.com/in/khayyamsaleem"
  identifier = "linkedin"
