title = "Khayyam Saleem"
baseUrl = "https://khayyam.me"

theme = "github.com/khayyamsaleem/ham-hugo"

[params]
  description = "ed-tech, functional programming, devops"

[markup.goldmark.renderer]
unsafe = true
