version: '2'

services:
  personalsite:
    image: registry.gitlab.com/khayyamsaleem/personalsite_v2:latest
    networks:
      - web
    labels:
      traefik.enable: "true"
      traefik.http.routers.personalsite.rule: "Host(`khayyam.me`)"
      traefik.http.routers.personalsite.entrypoints: https
      traefik.docker.network: "server_webgateway"
    restart: always

networks:
  web:
    external:
      name: server_webgateway
