version: '2'

services:
  personalsite:
    build: .
    image: khayyamsaleem/personal-site:${TAG}
    networks:
      - web
    labels:
      - "traefik.backend=personalsite"
      - "traefik.frontend.rule=Host: khayyam.me, www.khayyam.me"
      - "traefik.port=1313"
    restart: always

networks:
  web:
    external:
      name: server_webgateway
