version: '2'

services:
  personalsite:
    image: registry.gitlab.com/khayyamsaleem/personalsite_v2:latest
    networks:
      - web
    labels:
      - "traefik.backend=personalsite"
      - "traefik.frontend.rule=Host: khayyam.me, www.khayyam.me"
      - "traefik.port=1313"
    restart: always

networks:
  web:
    external:
      name: server_webgateway
