#+STARTUP: noindent showall
#+AUTHOR: Khayyam Saleem
#+HUGO_BASE_DIR: .
#+HUGO_AUTO_SET_LASTMOD: t

* Pages
:PROPERTIES:
:EXPORT_HUGO_MENU: :menu main
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :noauthor true :nodate true
:EXPORT_HUGO_SECTION: pages
:VISIBILITY: children
:END:

** DONE About                                                 :blog:about:
:PROPERTIES:
:EXPORT_FILE_NAME: about-me
:END:

I'm a soon-to-be-graduating senior at Stevens Institute of Technology, studying Computer Science. Strong passion for ed-tech, so this is where I'll be documenting the effort I'm making towards pursuing that passion. Feel free to reach out to me via [[mailto:ksaleem@stevens.edu][email]].

You can find my resume [[./static/resume.pdf][here]].


* Posts
:PROPERTIES:
:EXPORT_HUGO_SECTION: posts
:END:

** Meta                                                            :@meta:

*** DONE Moving to Hugo through Org                           :blog:about:
CLOSED: [2018-12-25 Tue 8:00]
:PROPERTIES:
:EXPORT_FILE_NAME: moving-to-hugo
:VISIBILITY: children
:END:

I want to try this new blog format. Since I've really started to enjoy org-mode in emacs, and I think that the themes in [[http://gohugo.io][Hugo]] seemed pretty, this was a natural choice. *Will* post a tutorial about my blog creation and deployment soon. Just a test for now.

**** Source Blocks

Below is a demo of a source block and its execution.

#+BEGIN_SRC ocaml
  let rec fact_h x acc = match x with
    | 1 -> acc
    | n -> fact_h (n-1) (n*acc) in
      let fact y = fact_h y 1 in
      fact 5
#+END_SRC

#+RESULTS:
: 120

**** Tables

Here's a demo of an org-mode table:

| Index | Value |
|-------|-------|
|     0 |     1 |
|     1 |     1 |
|     2 |     2 |
|     3 |     6 |
|     4 |    24 |
|     5 |   120 |


** DevOps :@devops:
*** DONE Deploying this Site                                       :devops:
CLOSED: [2018-12-25 Tue 19:35]
:PROPERTIES:
:EXPORT_FILE_NAME: deploying-this-blog
:VISIBILITY: children
:END:

This site is built with Hugo on org-mode. The site is deployed on a DigitalOcean droplet. The intent is to have it build with Jenkins and automatically update the site every time I push to master. As of now, I've been able to set up a CI/CD workflow. Currently working on adding git-hooks. It has been a wild ride.

**** Getting Started
First, prioritize getting everything going on your local version. Don't prioritize deployment until you at least have something to show, because it is quite a hassle to get going in the beginning.

* Footnotes
* COMMENT Local Variables :ARCHIVE:
# Local Variables:
# org-hugo-auto-export-on-save: t
# End:
