#+STARTUP: noindent showall
#+AUTHOR: Khayyam Saleem
#+HUGO_BASE_DIR: .
#+HUGO_AUTO_SET_LASTMOD: t

* Pages
:PROPERTIES:
:EXPORT_HUGO_MENU: :menu main
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :noauthor true :nodate true
:EXPORT_HUGO_SECTION: pages
:VISIBILITY: children
:END:

** About
:PROPERTIES:
:EXPORT_FILE_NAME: about-me
:END:

I'm a soon-to-be-graduating senior at Stevens Institute of Technology, studying Computer Science. Strong passion for ed-tech, so this is where I'll be documenting the effort I'm making towards pursuing that passion. Feel free to reach out to me through [[mailto:ksaleem@stevens.edu][email]]. You can find my resume [[./static/resume.pdf][here]].


* Posts
:PROPERTIES:
:EXPORT_HUGO_SECTION: posts
:END:

** Meta                                                            :@meta:

*** DONE Moving to Hugo through Org                       :meta:blog:about:
CLOSED: [2018-12-25 Tue 8:00]
:PROPERTIES:
:EXPORT_FILE_NAME: moving-to-hugo
:VISIBILITY: children
:END:

I want to try this new blog format. Since I've really started to enjoy org-mode in emacs, and I think that the themes in [[http://gohugo.io][Hugo]] seemed pretty, this was a natural choice. *Will* post a tutorial about my blog creation and deployment soon. Just a test for now.

**** Source Blocks

Below is a demo of a source block and its execution.

#+BEGIN_SRC ocaml
  let rec fact_h x acc = match x with
    | 1 -> acc
    | n -> fact_h (n-1) (n*acc) in
      let fact y = fact_h y 1 in
      fact 5
#+END_SRC

#+RESULTS:
: 120

**** Tables

Here's a demo of an org-mode table:

| Index | Value |
|-------|-------|
|     0 |     1 |
|     1 |     1 |
|     2 |     2 |
|     3 |     6 |
|     4 |    24 |
|     5 |   120 |

*** TODO Next Post
:PROPERTIES:
:EXPORT_FILE_NAME: draft-post
:END:

This is a draft post.\\
Here's another line.

* Footnotes
* COMMENT Local Variables :ARCHIVE:
# Local Variables:
# org-hugo-auto-export-on-save: t
# End:
